### ISSUE TITLE
GeoFencing Using Mobile Number

### ISSUE THREAD

**Issue by guruvishnuvardan** [sam-drew/picket#4]
Hi,

Good Day!

I am learning this GeoFencing tech now, Can you please let me know, if I can use this code to check if my customer is near my shop's premises, using my customers mobile number?

What can I do to implement that functionality.

Can you please clarify me?

Thanks
Guru

**Comment by sam-drew** [comment]
Hi! Geofencing using only a phone number is not something that is within the scope of this project, as it would almost certainly lead to privacy violations, and to be honest I don't even think it's possible without access to telecoms tower data (or some other relevant data).

This project is designed to check whether a known location is within a polygon formed from other known locations, not to solve the problem of determining the location of an object in the first place.

Hope that clears things up!

Cheers,
Sam
